"""Download the self-hosted fonts used by the hand-drawn design system.

LXGW WenKai (OFL, handwritten annotations), Fraunces (OFL, Latin display) and
Courier Prime (OFL, typewritten slates). Browsers fetch only the WenKai chunks
whose unicode-range is used on the page. Run from the project root.
"""
import re
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'public/fonts'
UA = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'}
WENKAI = 'https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.7.0'
GOOGLE = ('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT,WONK@9..144,300..700,0..100,0..1'
          '&family=Courier+Prime:wght@400;700&display=swap')


def get(url: str, attempts: int = 5) -> bytes:
    for attempt in range(attempts):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as response:
                return response.read()
        except OSError:
            if attempt == attempts - 1:
                raise
            time.sleep(1 + attempt)


def wenkai() -> str:
    (OUT / 'wenkai').mkdir(parents=True, exist_ok=True)
    css = get(f'{WENKAI}/lxgwwenkai-regular.css').decode('utf-8')
    for name in sorted(set(re.findall(r'files/(lxgwwenkai-regular-subset-\d+\.woff2)', css))):
        target = OUT / 'wenkai' / name
        if not target.exists():
            target.write_bytes(get(f'{WENKAI}/files/{name}'))
    (OUT / 'wenkai' / 'OFL.txt').write_bytes(get(f'{WENKAI}/OFL.txt'))
    css = re.sub(r'''url\(["']?\.?/?files/([^"')]+)["']?\)''', r'url(/fonts/wenkai/\1)', css)
    css = re.sub(r"font-family:\s*['\"]?LXGW WenKai['\"]?", "font-family:'Wenkai Hand'", css)
    return css


def google() -> str:
    css = get(GOOGLE).decode('utf-8')
    blocks = re.findall(r'/\* ([\w-]+) \*/\s*(@font-face\s*{[^}]*})', css)
    kept = []
    for subset, block in blocks:
        if subset != 'latin':
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r'font-weight: ([\d ]+);', block).group(1).replace(' ', '-')
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)
        name = f"{family.lower().replace(' ', '-')}-{weight}.woff2"
        (OUT / name).write_bytes(get(url))
        kept.append(block.replace(url, f'/fonts/{name}'))
    return '\n'.join(kept)


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    text = '/* Generated by production/fonts/fetch_fonts.py. All fonts are SIL OFL 1.1. */\n'
    text += google() + '\n' + wenkai()
    (OUT / 'fonts.css').write_text(text, encoding='utf-8')
    print('fonts.css', len(text), 'bytes;', sum(1 for _ in (OUT / 'wenkai').glob('*.woff2')), 'wenkai chunks')
