import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
manifest = json.loads((root / 'visuals/reference-v3/manifest.json').read_text(encoding='utf-8-sig'))
routes = ['opening', 'system-one', 'system-one/3', 'judgment/2', 'comparison/2', 'training/2', 'primitives/2', 'choice/2', 'noul/2', 'score/2', 'voice', 'economy']
cards = []
for item, route in zip(manifest, routes):
    name, title = item['id'], item['title']
    cards.append(f'''<article><header><h2>{title}</h2><a href="/#${route}" target="_blank">打开演示 ↗</a></header><div class="compare" style="--split:50%"><img src="{name}.png" alt="{title}实际页面"><img class="reference" src="../reference-art/ref-{name}.png" alt="{title}参考图"><i></i><b class="left">参考</b><b class="right">实现</b></div><div class="controls"><button data-action="actual">仅实现</button><input aria-label="{title}对照位置" type="range" min="0" max="100" value="50"><button data-action="reference">仅参考</button><button data-action="expand">放大 ↗</button></div></article>'''.replace('/#$', '/#'))
html = '''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Jev · 逐页参考对照</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4efe4;color:#262420;font:16px/1.6 system-ui}main{max-width:1500px;margin:auto;padding:36px 30px}h1{font-size:34px;margin:0 0 10px}p{margin:8px 0 25px;color:#686057}nav{display:flex;gap:25px;margin-bottom:28px}a{color:#a13b22}section{display:grid;grid-template-columns:1fr 1fr;gap:32px}article{min-width:0}article header{display:flex;justify-content:space-between;align-items:center}h2{font-size:20px;font-weight:600}.compare{position:relative;aspect-ratio:1672/941;overflow:hidden;box-shadow:0 4px 15px #33241416}.compare img{position:absolute;inset:0;width:100%;height:100%;display:block}.compare .reference{clip-path:inset(0 calc(100% - var(--split)) 0 0)}.compare i{position:absolute;left:var(--split);top:0;bottom:0;width:2px;background:#a33a20}.compare b{position:absolute;top:6px;background:#fcf7eddd;padding:2px 8px;font-size:12px}.compare .left{left:6px}.compare .right{right:6px}.controls{display:flex;align-items:center;gap:8px;margin:12px 0}.controls input{flex:1;min-width:40px;accent-color:#a13b22}button{border:1px solid #c7baa5;background:#fbf7ee;color:#3a342b;font:inherit;font-size:13px;padding:6px 10px;cursor:pointer}dialog{width:min(98vw,1700px);max-width:none;max-height:96vh;background:#f4efe4;padding:20px;border:1px solid #a99882}dialog::backdrop{background:#25221db8}dialog article{max-width:calc((90vh - 100px)*1672/941);margin:auto}dialog>button{float:right}footer{margin-top:40px;font-size:14px;color:#72685a}@media(max-width:950px){section{grid-template-columns:1fr}main{padding:22px 14px}}
</style><main><h1>Jev · 逐页参考对照</h1><p>拖动滑块比较同一位置。左边是参考图，右边是浏览器实际截图。动画请打开演示查看；O 键可在演示中叠图。原生字体笔画和部分素材纹理仍与生成参考图存在差异。</p><nav><a href="/#opening">进入正式演示 ↗</a><a href="/?motion-qa#opening">动画逐帧检查 ↗</a></nav><section>''' + ''.join(cards) + '''</section><footer>截图尺寸 1672 × 941。语音页截取按稿朗读后的停留状态；小镇保留原地图、人物与实验机制，没有替换成参考图片。</footer></main><dialog><button id="close">关闭 ×</button><div id="large"></div></dialog><script>
const dialog=document.querySelector('dialog');document.addEventListener('input',e=>{if(e.target.matches('input[type=range]'))e.target.closest('article').querySelector('.compare').style.setProperty('--split',e.target.value+'%')});document.addEventListener('click',e=>{const action=e.target.dataset.action;if(!action)return;const article=e.target.closest('article');if(action==='expand'){document.querySelector('#large').replaceChildren(article.cloneNode(true));dialog.showModal();return}const value=action==='actual'?0:100;article.querySelector('input').value=value;article.querySelector('.compare').style.setProperty('--split',value+'%')});document.querySelector('#close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
</script></html>'''
(root/'public/reference-review/index.html').write_text(html,encoding='utf-8')
print('Wrote review gallery for', len(cards), 'states')
