import type {CSSProperties,ReactNode} from 'react';

export const DESIGN={width:1672,height:941};
export type Box=readonly [number,number,number,number];
export function Text({x,y,w,size=32,weight=400,color,align='left',line=1.35,children,className='',style={}}:{x:number;y:number;w?:number;size?:number;weight?:number;color?:string;align?:'left'|'center'|'right';line?:number;children:ReactNode;className?:string;style?:CSSProperties}){
 return <div className={`r-text ${className}`} style={{left:x,top:y,width:w,fontSize:size,fontWeight:weight,color,textAlign:align,lineHeight:line,...style}}>{children}</div>;
}
export function Art({src,box=[0,0,1672,941],className='',style={}}:{src:string;box?:Box;className?:string;style?:CSSProperties}){const[x,y,w,h]=box;return <div className={`r-art ${className}`} style={{left:x,top:y,width:w,height:h,...style}} aria-hidden="true"><img src={`/reference-art/${src}.png`} draggable={false} style={{left:-x,top:-y,width:1672,height:941}}/></div>}
export function Group({show=true,children,className='',delay=0,style={}}:{show?:boolean;children:ReactNode;className?:string;delay?:number;style?:CSSProperties}){return <div className={`r-group ${show?'is-shown':''} ${className}`} style={{'--delay':`${delay}ms`,...style} as CSSProperties} aria-hidden={!show} inert={!show}>{children}</div>}
export function Ink({d,color='var(--r-ink)',width=3,show=true,delay=0,arrow=false}:{d:string;color?:string;width?:number;show?:boolean;delay?:number;arrow?:boolean}){return <path d={d} fill="none" stroke={color} strokeWidth={width} strokeLinecap="round" strokeLinejoin="round" pathLength="1" className={`r-ink-path ${show?'drawn':''}`} style={{transitionDelay:`${delay}ms`}} markerEnd={arrow?'url(#r-arrow)':undefined}/>}
export function Diagram({children,className=''}:{children:ReactNode;className?:string}){return <svg className={`r-diagram ${className}`} viewBox="0 0 1672 941" fill="none" aria-hidden="true"><defs><radialGradient id="r-grain-light" cx="30%" cy="20%" r="80%"><stop stopColor="white" stopOpacity=".23"/><stop offset=".55" stopColor="white" stopOpacity="0"/><stop offset="1" stopColor="black" stopOpacity=".22"/></radialGradient><marker id="r-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M1 1L8 5L1 9" fill="none" stroke="context-stroke" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></marker></defs>{children}</svg>}
export function Line({x,y,w,color='var(--r-rule)'}:{x:number;y:number;w:number;color?:string}){return <i className="r-rule" style={{left:x,top:y,width:w,background:color}}/>}
